language: javascript
node_js:
  - "11"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm i
  - npm run build

dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
